In [1]:
import pandas as pd
import re
import numpy as np

In [2]:
JP_addresses = pd.read_csv('/Users/oscar/Desktop/Exercise4_JP_addresses.csv')
JP_addresses.head()

,name,address,city,country
0,ほっともっと手稲曙店,"Japan, 〒006-0833 Hokkaido, Sapporo, Teine Ward...",Sapporo,JP
1,味の豊田,"1 Chome-13-10 Iizuka, Kawaguchi, Saitama 332-0...",Kawaguchi,JP
2,銭形事務所,"2 Chome-11-36 Sakaecho, Joetsu, Niigata 942-00...",Joetsu,JP
3,manchos！,"アルパ芦屋西 20 1, 1 Matsunouchicho, Ashiya, Hyogo 6...",Ashiya,JP
4,小林製菓,"572-6 Babacho, Hitachiota, Ibaraki 313-0004, J...",Hitachiota,JP

In [4]:
zipcodes=[]
for i in  JP_addresses.index:
    x = re.findall('\d{3}[-.\s]\d{4}', str(JP_addresses['address'][i]))
    if len(x) > 0:
        zipcodes.append(x[0])
    else:
        zipcodes.append('empty')

JP_addresses['zipcode'] = zipcodes
JP_addresses['zipcode']

0       006-0833
1       332-0023
2       942-0072
3       659-0094
4       313-0004
          ...
9995    904-2172
9996    512-0923
9997    367-0041
9998    900-0014
9999    819-1334
Name: zipcode, Length: 10000, dtype: object

In [6]:
street=[]
for i in  JP_addresses.index:
    split_data = str(JP_addresses['address'][i]).split(",")
    if split_data[0]=='Japan':
        street.append(split_data[-1])
    else:
        street.append(split_data[0])

JP_addresses['Street'] = street
JP_addresses['Street']

JP_addresses

,name,address,city,country,zipcode,Street
0,ほっともっと手稲曙店,"Japan, 〒006-0833 Hokkaido, Sapporo, Teine Ward...",Sapporo,JP,006-0833,曙3条3丁目14-37
1,味の豊田,"1 Chome-13-10 Iizuka, Kawaguchi, Saitama 332-0...",Kawaguchi,JP,332-0023,1 Chome-13-10 Iizuka
2,銭形事務所,"2 Chome-11-36 Sakaecho, Joetsu, Niigata 942-00...",Joetsu,JP,942-0072,2 Chome-11-36 Sakaecho
3,manchos！,"アルパ芦屋西 20 1, 1 Matsunouchicho, Ashiya, Hyogo 6...",Ashiya,JP,659-0094,アルパ芦屋西 20 1
4,小林製菓,"572-6 Babacho, Hitachiota, Ibaraki 313-0004, J...",Hitachiota,JP,313-0004,572-6 Babacho
...,...,...,...,...,...,...
9995,あきない,"6 Chome-25-2 Awase, Okinawa, 904-2172, Japan",Okinawa,JP,904-2172,6 Chome-25-2 Awase
9996,まつかさ,"2519-1 Takatsunocho, Yokkaichi, Mie 512-0923, ...",Yokkaichi,JP,512-0923,2519-1 Takatsunocho
9997,珈琲横丁,"駅南５５ビル 2f, 1 Chome-10-５ Ekinan, Honjo, Saitama...",Honjo,JP,367-0041,駅南５５ビル 2f
9998,Noi Caphe (Vietnamese Pho),"Japan, 〒900-0014 Okinawa, Naha, Matsuo, 2 Chom...",Naha,JP,900-0014,2 Chome−10−20 ちとせ商店街ビル
9999,イタリアン食堂 トラットリア ジロ,"3-3 Shimakishi, Itoshima, Fukuoka 819-1334, Japan",Itoshima,JP,819-1334,3-3 Shimakishi